title: Scruffy Notes
author: Aryan Agal
email: <FirstName><LastName><Nine><Eight>@gmail.com
description: Cheap profundity is sold here

github_username: grubdragon
instagram_username: aryanagal
# twitter_username:
# facebook_username:
# dribbble_username:

# date_format:
timezone: Asia/Kolkata

google_analytics: G-8V1D8SY4ED
# disqus_shortname:

blog_theme: auto
# light-theme-accent-color: '#333'
# dark-theme-accent-color: '#eee'

markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jemoji
